# %% UNIT TESTING FOR hfatlas to rafts prep workflow
# Auto-generated by Gemini3Pro
import pyarrow.parquet as pq
from shapely.geometry import Point, LineString, MultiLineString
import tempfile
import geopandas as gpd
import pandas as pd
import numpy as np
import unittest
from pathlib import Path
import sqlite3

# Assuming the target functions are imported from the relevant script (e.g., hfatlas_to_rafts_prep)
# For the sake of this testing block, we assume they are accessible in the current namespace 
# or imported as: 
import rafts_algo.utils as raftsutil

class TestHfAtlasToRaftsPrep(unittest.TestCase):
    
    def setUp(self):
        """Set up real files in a temporary directory to avoid mocking I/O logic."""
        self.temp_dir = tempfile.TemporaryDirectory()
        self.test_path = Path(self.temp_dir.name)
        
        # 1. Create a dummy hfATLAS Parquet file with pint-aware string columns
        self.df_hfatlas = pd.DataFrame({
            "divide_id": ["div1", "div2", "div3"],
            "('TOT_AET', 'mm')": [10.5, 20.1, np.nan],
            "('ELEV', 'm')": [100, 200, 300],
            "normal_col": [1, 2, 3]
        })
        self.path_hfatl_pq = self.test_path / "test_hfatlas.parquet"
        self.df_hfatlas.to_parquet(self.path_hfatl_pq)
        
        # 2. Create a dummy Hydrofabric GeoPackage (using Fiona/GeoPandas to write it)
        self.gdf_hf = gpd.GeoDataFrame({
            "divide_id": ["div1", "div2"],
            "vpuid": ["01", "02"]
        }, geometry=[
            LineString([(0, 0), (2, 2), (4, 4)]), # Midpoint will be (2,2)
            LineString([(1, 1), (3, 3)])          # Midpoint will be (2,2) mathematically
        ], crs="EPSG:4326")
        
        self.path_hf_gpkg = self.test_path / "test_hf.gpkg"
        self.gdf_hf.to_file(self.path_hf_gpkg, driver="GPKG", layer="flowpaths")

    def tearDown(self):
        """Clean up the temporary directory."""
        self.temp_dir.cleanup()

    # --- Tests ---

    def test_clean_hfatlas_columns(self):
        """Test the parsing of pint-aware column names."""
        df = pd.DataFrame(columns=["normal", "('TOT_AET', 'mm')", "('bad_tuple)"])
        cleaned_df = raftsutil.clean_hfatlas_columns(df)
        
        expected_cols = ["normal", "TOT_AET", "('bad_tuple)"]
        self.assertListEqual(list(cleaned_df.columns), expected_cols)

    def test_resolve_fstrings_and_safedict(self):
        """Test the recursive f-string resolver."""
        context = {"home_dir": "/my/home", "ds": "camels"}
        
        # Standard replacement
        val1 = "{home_dir}/data/{ds}"
        self.assertEqual(raftsutil.resolve_fstrings(val1, context), "/my/home/data/camels")
        
        # Missing key should be left alone
        val2 = "{home_dir}/data/{missing_key}"
        self.assertEqual(raftsutil.resolve_fstrings(val2, context), "/my/home/data/{missing_key}")

    def test_get_middle_vertex(self):
        """Test coordinate extraction from Linestrings."""
        line = LineString([(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])
        pt = raftsutil.get_middle_vertex(line)
        self.assertEqual(pt.x, 2.0)
        self.assertEqual(pt.y, 2.0)
        
        mline = MultiLineString([[(0, 0), (1, 1)], [(2, 2), (3, 3), (4, 4)]])
        pt2 = raftsutil.get_middle_vertex(mline)
        self.assertEqual(pt2.x, 2.0)
        self.assertEqual(pt2.y, 2.0)
        
        pt3 = raftsutil.get_middle_vertex(Point(0, 0))
        self.assertEqual(pt3.x, 0.0)
        self.assertEqual(pt3.y, 0.0)
        
    def test_read_hfatlas_wrap_dask(self):
        """Test PyArrow metadata reading, renaming, and Dask merging directly from disk."""
        attrs_sel = ["TOT_AET", "ELEV"]
        
        result_df = raftsutil.read_hfatlas_wrap_dask([self.path_hfatl_pq], attrs_sel, "divide_id")
        
        self.assertEqual(result_df.shape[0], 3)
        self.assertIn("TOT_AET", result_df.columns)
        self.assertIn("ELEV", result_df.columns)
        self.assertNotIn("('TOT_AET', 'mm')", result_df.columns) # Should be mapped cleanly
        
        # Check values
        self.assertEqual(result_df.loc[result_df["divide_id"] == "div1", "ELEV"].iloc[0], 100)

    def test_generate_algo_points_gpkg_wrap(self):
        """Test reading specific divides from a GeoPackage and formatting points."""
        div_ids = pd.Series(["div1"])
        path_out_gpkg = self.test_path / "dataset_out.gpkg"
        
        result_gdf = raftsutil.generate_algo_points_gpkg_wrap(
            div_ids=div_ids,
            path_hf_gpkg=self.path_hf_gpkg,
            path_gpkg_rafts_prep=path_out_gpkg,
            hf_layer="flowpaths",
            map_id_col="divide_id",
            featureSource="test_source"
        )
        
        self.assertEqual(result_gdf.shape[0], 1)
        self.assertEqual(result_gdf.iloc[0]["featureID"], "div1")
        self.assertEqual(result_gdf.iloc[0]["featureSource"], "test_source")
        
        # Check coordinate extraction logic (Middle vertex of div1 is (2,2))
        self.assertEqual(result_gdf.iloc[0]["X"], 2.0)
        self.assertEqual(result_gdf.iloc[0]["Y"], 2.0)
        
        # Ensure file was saved
        self.assertTrue(path_out_gpkg.exists())

    def test_hfatl_std_long(self):
        """Test wide-to-long reshaping of hfATLAS attributes."""
        df_wide = pd.DataFrame({
            "divide_id": ["div1"],
            "vpuid": ["01"],
            "TOT_AET": [10.5],
            "ELEV": [100]
        })
        
        df_long = raftsutil.hfatl_std_long(df_wide)
        
        self.assertEqual(df_long.shape[0], 2)
        self.assertListEqual(list(df_long.columns), ["divide_id", "vpuid", "attribute", "value"])
        self.assertIn("TOT_AET", df_long["attribute"].values)

    def test_generate_vpu_attr_filepath(self):
        """Test directory generation logic."""
        path = raftsutil.generate_vpu_attr_filepath(self.test_path, "my_dataset", "18")
        expected = self.test_path / "my_dataset" / "18" / "attr_18.parquet"
        
        self.assertEqual(path, expected)
        self.assertTrue(path.parent.exists())

    def test_hfatl_hf_cmbo_wrap(self):
        """Test combination logic and dynamic Parquet saving by VPU."""
        df_hfatlas = pd.DataFrame({
            "divide_id": ["div1", "div2"],
            "TOT_AET": [10.5, 20.0]
        })
        
        gdf_hf = gpd.GeoDataFrame({
            "divide_id": ["div1", "div2"],
            "vpuid": ["01", "02"]
        }, geometry=[Point(0,0), Point(1,1)])
        
        result_long = raftsutil.hfatl_hf_cmbo_wrap(
            df_hfatlas=df_hfatlas,
            gdf_hf=gdf_hf,
            ds="test_ds",
            dir_db_attrs=self.test_path,
            featureSource="hf_test",
            vpu_mapped=True
        )
        
        # Validate DataFrame return format
        self.assertIn("featureID", result_long.columns)
        self.assertIn("dl_timestamp", result_long.columns)
        self.assertEqual(result_long.loc[result_long["featureID"] == "div1", "vpuid"].iloc[0], "01")
        
        # Validate grouped saving to disk
        self.assertTrue((self.test_path / "test_ds" / "01" / "attr_01.parquet").exists())
        self.assertTrue((self.test_path / "test_ds" / "02" / "attr_02.parquet").exists())

    def test_read_hfatlas_wrap_dask_edge_cases(self):
        # 1. Hit the .is_dir() branch by passing the parent temp directory
        # 2. Hit the missing columns warning by asking for 'FAKE_ATTR'
        result_df = raftsutil.read_hfatlas_wrap_dask([self.test_path], ["TOT_AET", "FAKE_ATTR"], "divide_id")
        self.assertNotIn("FAKE_ATTR", result_df.columns)
        
        # 3. Hit the corrupt file exception branch by making a fake text file with a .parquet extension
        bad_parquet = self.test_path / "corrupt.parquet"
        bad_parquet.write_text("This is not a real parquet file")
        
        # This will safely catch the error in the try/except block, log a warning, and return empty
        with self.assertLogs(level='WARNING') as cm:
            raftsutil.read_hfatlas_wrap_dask([bad_parquet], ["TOT_AET"], "divide_id")
        self.assertTrue(any("Could not read schema" in log for log in cm.output))
    
    def test_generate_algo_points_gpkg_wrap_edge_cases(self):
        # Create a GPKG with POINTS instead of LineStrings to hit the `try` block (geometry.x)
        # Also omit the 'vpuid' column to trigger the missing VPU warning
        gdf_pts = gpd.GeoDataFrame({
            "divide_id": ["div1"]
        }, geometry=[Point(5, 5)], crs="EPSG:4326")
        
        path_pts_gpkg = self.test_path / "pts.gpkg"
        gdf_pts.to_file(path_pts_gpkg, driver="GPKG", layer="flowpaths")

        with self.assertLogs(level='WARNING') as cm:
            result_gdf = raftsutil.generate_algo_points_gpkg_wrap(
                div_ids=pd.Series(["div1"]),
                path_hf_gpkg=path_pts_gpkg,
                path_gpkg_rafts_prep=None, # Hit the branch that skips saving the output file
                hf_layer="flowpaths",
                map_id_col="divide_id"
            )
            
        self.assertTrue(any("Expecting vpuid vpu col" in log for log in cm.output))
        self.assertEqual(result_gdf.iloc[0]["X"], 5.0) # Confirms it hit the try block!

    def test_hfatl_hf_cmbo_wrap_edge_cases(self):
        df_hfatlas = pd.DataFrame({"divide_id": ["div1"], "TOT_AET": [10.5]})
        gdf_hf = gpd.GeoDataFrame({"divide_id": ["div1"], "vpuid": ["01"]}, geometry=[Point(0,0)])
        
        # 1. Hit the vpu_mapped=False branch
        result_long = raftsutil.hfatl_hf_cmbo_wrap(
            df_hfatlas=df_hfatlas, gdf_hf=gdf_hf, ds="test_ds",
            dir_db_attrs=self.test_path, featureSource="hf_test",
            vpu_mapped=False # <-- Triggers the 'all' vpuid override
        )
        self.assertEqual(result_long.iloc[0]["vpuid"], "all")
        
        # 2. Hit the sys.exit(1) branch by passing completely EMPTY dataframes
        df_empty = pd.DataFrame(columns=["divide_id", "TOT_AET"])
        gdf_empty = gpd.GeoDataFrame(columns=["divide_id", "vpuid", "geometry"], crs="EPSG:4326")
        
        # Catch the SystemExit so it doesn't crash the test runner!
        with self.assertRaises(SystemExit):
            raftsutil.hfatl_hf_cmbo_wrap(
                df_hfatlas=df_empty, gdf_hf=gdf_empty, ds="test_ds",
                dir_db_attrs=self.test_path, featureSource="hf_test"
            )

    def test_generate_vpu_attr_filepath_redundant_name(self):
        # Pass a dir_db_attrs that ALREADY contains the dataset name ('my_dataset')
        path_with_ds = self.test_path / "my_dataset"
        
        path = raftsutil.generate_vpu_attr_filepath(path_with_ds, "my_dataset", "18")
        
        # It should NOT duplicate 'my_dataset/my_dataset' in the final path
        expected = self.test_path / "my_dataset" / "18" / "attr_18.parquet"
        self.assertEqual(path, expected)

    def test_get_middle_vertex_empty(self):
        # Hit the fallback conditions at the top of the function
        self.assertIsNone(raftsutil.get_middle_vertex(None))
        self.assertIsNone(raftsutil.get_middle_vertex(LineString()))

class TestDiscoverDynamicAlgos(unittest.TestCase):
    def test_discover_dynamic_algos(self):
        """Test the dynamic extraction of model names from files on disk without mocking."""
        with tempfile.TemporaryDirectory() as tmpdir:
            search_dir = Path(tmpdir)
            
            # Create physically real, empty dummy files on the disk
            (search_dir / "algo_kmeans_k5_my_metric__my_ds.joblib").touch()
            (search_dir / "algo_rf_my_metric__my_ds.joblib").touch()
            (search_dir / "ignore_me.txt").touch() # Noise file to ensure strict filtering

            # Execute the function
            discovered = raftsutil.discover_dynamic_algos(
                search_dir=search_dir,
                base_algos=['kmeans', 'rf'],
                metric='my_metric',
                dataset_id='my_ds',
                file_prefix='algo_',
                file_extension='.joblib'
            )
            
            # Validate it found the exact algorithm strings required to load them
            self.assertCountEqual(discovered, ['kmeans_k5', 'rf'])

class TestHfAtlasUnitMapper(unittest.TestCase):
    def test_unit_mapper_creation_and_saving(self):
        """Test parsing pint-tuples and physically writing the mapper CSV."""
        raw_cols = ["normal_col", "('TOT_AET', 'mm')"]
        
        # 1. Test DataFrame Creation logic
        mapper_df = raftsutil.create_hfatlas_unit_mapper(raw_cols)
        self.assertEqual(len(mapper_df), 2)
        self.assertEqual(mapper_df.iloc[1]['clean_column'], 'TOT_AET')
        self.assertEqual(mapper_df.iloc[1]['unit'], 'mm')
        
        # 2. Test Physical File Saving
        with tempfile.TemporaryDirectory() as tmpdir:
            out_dir = Path(tmpdir)
            
            saved_path = raftsutil.save_hfatlas_unit_mapper(
                mapper_df=mapper_df,
                dir_std_base=out_dir,
                ds="my_ds",
                cstm_str="test"
            )
            
            # Assert the file exists on the OS
            self.assertTrue(saved_path.exists())
            
            # Verify we can read it back natively
            read_df = pd.read_csv(saved_path)
            self.assertEqual(read_df.iloc[1]['unit'], 'mm')

class TestRegionalizationPaths(unittest.TestCase):
    def test_donor_pairing_and_receiver_paths(self):
        """Test that regionalization output paths are formatted correctly and parents are created."""
        with tempfile.TemporaryDirectory() as tmpdir:
            base = Path(tmpdir)
            
            # Test donor pairing path
            p1 = raftsutil.std_donor_pairs_path(base, 'my_ds', 'rf', 'param_a')
            self.assertEqual(p1.name, 'donor_pairs_rf_param_a__my_ds.csv')
            self.assertTrue(p1.parent.exists()) # Verifies mkdir(parents=True) worked
            
            # Test mapped gpkg path
            p2 = raftsutil.std_receiver_params_mapped_path(base, 'my_ds', 'rf', 'param_a', ext='.gpkg')
            self.assertEqual(p2.name, 'receiver_params_mapped_rf_param_a__my_ds.gpkg')

            # Test imputation log path
            p3 = raftsutil.std_impute_log_path(base, 'my_ds', 'rf', 'param_a')
            self.assertEqual(p3.name, 'imputed_locations_rf_param_a__my_ds.csv')

class TestHfAtlasParsing(unittest.TestCase):

    def test_parse_hfatlas_colname_tuple_with_unit(self):
        """Test parsing a string representation of a tuple with a clean name and a unit."""
        raw = "('TOT_AET_hfa', 'millimeter')"
        clean_name, unit = raftsutil.parse_hfatlas_colname(raw)
        self.assertEqual(clean_name, "TOT_AET_hfa")
        self.assertEqual(unit, "millimeter")

    def test_parse_hfatlas_colname_tuple_no_unit(self):
        """Test parsing a tuple that only contains a clean name."""
        raw = "('TOT_ELEV',)"
        clean_name, unit = raftsutil.parse_hfatlas_colname(raw)
        self.assertEqual(clean_name, "TOT_ELEV")
        self.assertIsNone(unit)

    def test_parse_hfatlas_colname_not_a_tuple(self):
        """Test parsing a standard string that is not formatted as a tuple."""
        raw = "normal_column_name"
        clean_name, unit = raftsutil.parse_hfatlas_colname(raw)
        self.assertEqual(clean_name, "normal_column_name")
        self.assertIsNone(unit)

    def test_parse_hfatlas_colname_malformed_tuple(self):
        """Test parsing a malformed tuple string that throws an evaluation error."""
        raw = "('TOT_AET_hfa', 'millimeter'"  # Missing closing parenthesis
        clean_name, unit = raftsutil.parse_hfatlas_colname(raw)
        self.assertEqual(clean_name, raw)
        self.assertIsNone(unit)

    def test_clean_hfatlas_columns(self):
        """Test renaming dataframe columns from raw pint-tuples to clean strings."""
        df = pd.DataFrame(columns=[
            "('TOT_AET_hfa', 'millimeter')", 
            "('TOT_ELEV',)", 
            "normal_col"
        ])
        cleaned_df = raftsutil.clean_hfatlas_columns(df)
        expected_cols = ["TOT_AET_hfa", "TOT_ELEV", "normal_col"]
        self.assertListEqual(list(cleaned_df.columns), expected_cols)

    def test_create_hfatlas_unit_mapper(self):
        """Test the creation of the hfATLAS mapping dataframe."""
        raw_cols = [
            "('TOT_AET_hfa', 'millimeter')", 
            "normal_col",
            "('TOT_PRSNOW', 'percent')"
        ]
        
        mapper_df = raftsutil.create_hfatlas_unit_mapper(raw_cols)
        
        self.assertEqual(mapper_df.shape[0], 3)
        self.assertListEqual(list(mapper_df.columns), ['raw_column', 'clean_column', 'unit'])
        
        # Verify first row
        self.assertEqual(mapper_df.iloc[0]['raw_column'], "('TOT_AET_hfa', 'millimeter')")
        self.assertEqual(mapper_df.iloc[0]['clean_column'], "TOT_AET_hfa")
        self.assertEqual(mapper_df.iloc[0]['unit'], "millimeter")
        
        # Verify second row (no unit)
        self.assertEqual(mapper_df.iloc[1]['raw_column'], "normal_col")
        self.assertEqual(mapper_df.iloc[1]['clean_column'], "normal_col")
        self.assertTrue(pd.isna(mapper_df.iloc[1]['unit']))

class TestGeomAndResolvers(unittest.TestCase):
    def test_resolve_fstrings(self):
        """Test the recursive f-string resolver logic."""
        context = {"home_dir": "/user/home", "ds": "camels"}
        
        # Standard Replacement
        val1 = "{home_dir}/data/{ds}"
        self.assertEqual(raftsutil.resolve_fstrings(val1, context), "/user/home/data/camels")
        
        # Missing keys are safely ignored
        val2 = "{home_dir}/data/{missing_key}"
        self.assertEqual(raftsutil.resolve_fstrings(val2, context), "/user/home/data/{missing_key}")
        
        # Max depth safety (Recursive substitution)
        val3 = "{home_dir}/data/{recursive_dir}"
        context_recursive = {"home_dir": "/user/home", "recursive_dir": "{ds}/stuff", "ds": "camels"}
        self.assertEqual(raftsutil.resolve_fstrings(val3, context_recursive, max_depth=3), "/user/home/data/camels/stuff")

    def test_get_middle_vertex(self):
        """Test coordinate extraction for geometric midpoints."""
        # LineString Midpoint
        line = LineString([(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])
        pt = raftsutil.get_middle_vertex(line)
        self.assertEqual(pt.x, 2.0)
        self.assertEqual(pt.y, 2.0)
        
        # MultiLineString Midpoint
        mline = MultiLineString([[(0, 0), (1, 1)], [(2, 2), (3, 3), (4, 4)]])
        pt2 = raftsutil.get_middle_vertex(mline)
        self.assertEqual(pt2.x, 2.0)
        self.assertEqual(pt2.y, 2.0)
        
        # Points pass through
        pt3 = raftsutil.get_middle_vertex(Point(5, 5))
        self.assertEqual(pt3.x, 5.0)
        self.assertEqual(pt3.y, 5.0)
        
        # Empty/None fallbacks
        self.assertIsNone(raftsutil.get_middle_vertex(None))
        self.assertIsNone(raftsutil.get_middle_vertex(LineString()))

class TestReadHfatlasWrapDask(unittest.TestCase):
    def setUp(self):
        """Set up physically real Parquet files in a temporary directory for Dask."""
        self.temp_dir = tempfile.TemporaryDirectory()
        self.test_path = Path(self.temp_dir.name)
        
        # Generate DataFrame with raw tuple column names
        self.df_hfatlas = pd.DataFrame({
            "divide_id": ["div1", "div2", "div3"],
            "vpuid": ["01", "02", "01"],
            "('TOT_AET', 'mm')": [10.5, 20.1, np.nan],
            "('ELEV', 'm')": [100, 200, 300]
        })
        
        self.path_hfatl_pq = self.test_path / "test_hfatlas.parquet"
        self.df_hfatlas.to_parquet(self.path_hfatl_pq)

    def tearDown(self):
        self.temp_dir.cleanup()

    def test_read_hfatlas_wrap_dask_success(self):
        """Test successful Dask loading, parsing, and joining of hfATLAS Parquet."""
        attrs_sel = ["TOT_AET", "ELEV"]
        
        # Run function on the real, temporary Parquet file
        result_df = raftsutil.read_hfatlas_wrap_dask(
            paths_hfatl=[self.path_hfatl_pq], 
            attrs_sel=attrs_sel, 
            map_id_col="divide_id",
            query_clean=True # Cleans NaN values/units
        )
        
        self.assertEqual(result_df.shape[0], 3)
        self.assertIn("TOT_AET", result_df.columns)
        self.assertIn("ELEV", result_df.columns)
        self.assertNotIn("('TOT_AET', 'mm')", result_df.columns) # Verifies tuple parser worked
        self.assertIn("divide_id", result_df.columns) # ID column retained
        self.assertTrue(pd.api.types.is_string_dtype(result_df["divide_id"])) # ID coerced to string safely

    def test_read_hfatlas_wrap_dask_missing_columns(self):
        """Test behavior when requested attributes are not physically in the file."""
        # 'FAKE_ATTR' does not exist in the Parquet file
        result_df = raftsutil.read_hfatlas_wrap_dask(
            paths_hfatl=[self.path_hfatl_pq], 
            attrs_sel=["TOT_AET", "FAKE_ATTR"], 
            map_id_col="divide_id"
        )
        
        self.assertIn("TOT_AET", result_df.columns)
        self.assertNotIn("FAKE_ATTR", result_df.columns) # Safely ignored

    def test_read_hfatlas_wrap_dask_corrupt_file(self):
        """Test Dask fallback behavior when encountering unreadable or empty files."""
        bad_parquet = self.test_path / "corrupt.parquet"
        bad_parquet.write_text("This is not a real parquet file")
        
        with self.assertLogs(level='WARNING') as cm:
            result = raftsutil.read_hfatlas_wrap_dask([bad_parquet], ["TOT_AET"], "divide_id")
            
        self.assertTrue(any("Could not read schema" in log for log in cm.output))
        # Returns an empty dataframe with the requested schema
        self.assertTrue("TOT_AET" in result.columns)
        self.assertEqual(len(result), 0)

class TestDatabaseAndCrosswalks(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.test_path = Path(self.temp_dir.name)
        self.db_path = self.test_path / "test_regionalization.sqlite"

        # Create dummy gpkg table
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("CREATE TABLE gpkg_contents (table_name TEXT, data_type TEXT, identifier TEXT, description TEXT)")
        
        self.df_data = pd.DataFrame({
            "featureID": ["div1", "div2"],
            "param_a": [1.1, 2.2]
        })

    def tearDown(self):
        self.temp_dir.cleanup()

    def test_update_database_creation_and_registration(self):
        """Test physical SQLite database creation, indexing, and GPKG registration."""
        raftsutil.update_database(
            db_path=self.db_path, 
            df_data=self.df_data, 
            table_name="params", 
            id_col="featureID", 
            overwrite=True
        )
        
        self.assertTrue(self.db_path.exists())
        
        # Verify writing via native SQLite
        with sqlite3.connect(self.db_path) as conn:
            # 1. Verify Data Exists
            df_read = pd.read_sql_query("SELECT * FROM params", conn)
            self.assertEqual(len(df_read), 2)
            self.assertEqual(df_read.loc[df_read['featureID'] == 'div1', 'param_a'].iloc[0], 1.1)
            
            # 2. Verify Index was created
            cursor = conn.cursor()
            cursor.execute("SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='params'")
            indexes = [row[0] for row in cursor.fetchall()]
            self.assertIn("idx_params_featureID", indexes)
            
            # 3. Verify GeoPackage attributes table registration
            cursor.execute("SELECT table_name FROM gpkg_contents WHERE table_name='params'")
            registered = cursor.fetchone()
            self.assertIsNotNone(registered)

    def test_get_crosswalk_target_col(self):
        """Test the strict hierarchy of crosswalk target column resolution."""
        # Hierarchy: User Config -> Native Default -> Subtraction Fallback
        
        # 1. User Config Priority
        df_crosswalk = pd.DataFrame(columns=["divide_id", "comid", "custom_id_column", "some_value"])
        target = raftsutil.get_crosswalk_target_col(
            df_crosswalk, 
            pred_gpkg_id_col="divide_id", 
            crosswalk_target_col="custom_id_column"
        )
        self.assertEqual(target, "custom_id_column")
        
        # 2. Native Default (hydrofabric standards)
        df_crosswalk2 = pd.DataFrame(columns=["divide_id", "comid", "some_value"])
        target2 = raftsutil.get_crosswalk_target_col(
            df_crosswalk2, 
            pred_gpkg_id_col="divide_id", 
            crosswalk_target_col=None
        )
        self.assertEqual(target2, "divide_id")

        # 3. Subtraction Fallback (Isolates the remaining identifier)
        df_crosswalk3 = pd.DataFrame(columns=["prediction_id", "areasqkm", "vpuid", "mystery_topology_id"])
        target3 = raftsutil.get_crosswalk_target_col(
            df_crosswalk3, 
            pred_gpkg_id_col="prediction_id", 
            crosswalk_target_col=None
        )
        self.assertEqual(target3, "mystery_topology_id")

class TestStandardizationAndReshaping(unittest.TestCase):
    def test_hfatl_std_long(self):
        """Test wide-to-long reshaping of hfATLAS attributes while retaining identifiers."""
        df_wide = pd.DataFrame({
            "divide_id": ["div1"],
            "vpuid": ["01"],
            "TOT_AET": [10.5],
            "ELEV": [100]
        })
        
        df_long = raftsutil.hfatl_std_long(df_wide, map_id_col="divide_id", vpu_id_col="vpuid")
        
        self.assertEqual(df_long.shape[0], 2)
        self.assertListEqual(list(df_long.columns), ["divide_id", "vpuid", "attribute", "value"])
        self.assertIn("TOT_AET", df_long["attribute"].values)
        self.assertIn("ELEV", df_long["attribute"].values)
        self.assertEqual(df_long.loc[df_long['attribute'] == 'TOT_AET', 'value'].iloc[0], 10.5)

if __name__ == '__main__':
    unittest.main()