# Map locations & custom metadata of OCONUS nextgen hydrofabric gpkg files
# Make sure the name of this file is referenced in the corresponding attribute config file.
# Companion parsing function: proc.attr.hydfab::parse_hfab_oconus_config
dir_base_hfab: "{dir_base}/gpkg_dat" # The base directory containing the hydrofabric gpkg files in the R Package directory for unit testing, where `dir_base = system.file("extdata",package="proc.attr.hydfab")`
source_map_ak:
  path: "{dir_base_hfab}/test_ak_nextgen.gpkg"
source_map_pr:
  path: "{dir_base_hfab}/test_prvi_nextgen.gpkg"
source_map_vi:
  path: "{dir_base_hfab}/test_prvi_nextgen.gpkg"
source_map_hi:
  path: "{dir_base_hfab}/test_hi_nextgen.gpkg"
