#' @title Processing script to grab catchment attributes
#' @author Guy Litt \code{guy.litt@noaa.gov}
#' @description
#' Given catchment location data generated by rafts_prep and a user-specified
#' configuration file for datasets and corresponding attributes of interest,
#' acquire the attributes for each catchment, write to parquet database.
#' @details Builds a parquet database for each individual comid when calling
#' \code{proc.attr.hydfab::proc_attr_wrap}. From the directory of comids,
#' creates a sub-directory of a specific dataset.
#'
#' NOTE: In defining the featureSource and featureID, it's expected that the
#' term 'gage_id' is used as a variable in glue syntax to create featureID
#' @seealso [rafts_prep] A python package that processes input data for the
#' rafts
#' @usage Rscript rafts_attrs_grab.R "/path/to/attribute_config.yaml"

# Changelog / Contributions
#   2024-07-24 Originally created, GL

library(tibble)
library(yaml)
library(ncdf4)
library(proc.attr.hydfab)
library(glue)
library(future)
library(future.apply)
library(logr)

# Changelog/contributions
#. 2024 originally created, GL

# TODO add path_save_gpkg_custom to parsing in Retr_Params?? ...or as an argument in this rafts_attrs_grab.R
# Sys.setenv(AWS_NO_SIGN_REQUEST="YES")

# Define command line argument
cmd_args <- commandArgs("trailingOnly" = TRUE)

if(base::length(cmd_args)!=1){
  warning("Unexpected to have more than one argument in Rscript rafts_attrs_grab.R /path/to/attribute_config.yaml.")
}

# Read in config file, e.g.  "~/git/rafts/scripts/eval_ingest/xssa_us/xssaus_attr_config.yaml"
path_attr_config <- cmd_args[1] # "~/git/rafts/scripts/eval_ingest/xssa/xssa_attr_config.yaml"
Retr_Params <- proc.attr.hydfab::attr_cfig_parse(path_attr_config)
#-----------------------------------------------------
dir_log <- proc.attr.hydfab::std_dir_logs(Retr_Params$paths$dir_db_attrs)
path_log <- proc.attr.hydfab::std_path_log(dir_log,path_attr_config,script="rafts_attrs_grab")
logr::log_open(path_log)#file_name=base::basename(path_log),logdir=base::dirname(path_log))
logr::log_print(glue::glue("Running rafts_attrs_grab.R {path_attr_config} at {Sys.time()}"))
if(base::length(cmd_args)!=1){
  logr::log_print("Unexpected to have more than one argument in
                  Rscript rafts_attrs_grab.R /path/to/attribute_config.yaml.",
                  level="WARN")
}
#-----------------------------------------------------
logr::log_print(glue::glue("proc.attr.hydfab package version {packageVersion('proc.attr.hydfab')}"),
                level="INFO")

logr::log_print(glue::glue("Attribute dataset sources include the following:\n
  {paste0(names(Retr_Params$vars),collapse='\n')}"),level="INFO")

logr::log_print(glue::glue("Attribute variables to be acquired include :
  \n{paste0(unlist(unname(Retr_Params$vars)),collapse='\n')}"),level="print")


# PROCESS ATTRIBUTES
dt_comids <- proc.attr.hydfab:::grab_attrs_datasets_rafts_wrap(Retr_Params,
                                                      lyrs="network",
                                                      overwrite = FALSE,
                                                      path_save_gpkg_cstm=NULL)
logr::log_close()
# --------------------------- Compile attributes --------------------------- #
# Demonstration of how to retrieve attributes/comids that exist inside dir_db_attrs:
demo_example <- FALSE
if (demo_example){
  # The comids of interest
  comids <- dt_comids$featureID %>% base::unname() %>% base::unlist()

  # The attribute variables of interest
  vars <- Retr_Params$vars %>% base::unlist() %>% base::unname()

  dat_all_attrs <- proc.attr.hydfab::retrieve_attr_exst(comids, vars,
                                                        Retr_Params$paths$dir_db_attrs)
  base::rm(dat_all_attrs)

}

