#' @title Test case to use for algorithm prediction
#' @author Guy Litt
#' @description Selects a small sample of US locations (20) from the Julie Mai xSSA
#' dataset and generates attributes to use for testing algo prediction capabilities

library(dplyr)
library(glue)
library(tidyr)
library(yaml)

main <- function(){
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) < 1) {
    stop("Input prediction configuration file must be specified")
  }

  home_dir <- Sys.getenv("HOME")
  path_cfig_pred <- glue::glue(as.character(args[1]))
  subsamp_n <- ifelse(length(args) >= 2, base::as.integer(args[2]), 20)
  subsamp_seed <- ifelse(length(args) >=3, base::as.integer(args[3]), 432)

  if(!base::file.exists(path_cfig_pred)){
    stop(glue::glue("The provided path_cfig_pred does not exist: {path_cfig_pred}"))
  }

  cfig_pred <- yaml::read_yaml(path_cfig_pred)
  path_meta <- base::unlist(cfig_pred)[['path_meta']]

  # READ IN ATTRIBUTE CONFIG FILE
  name_attr_config <- cfig_pred$name_attr_config
  path_attr_config <- proc.attr.hydfab::build_cfig_path(path_cfig_pred, name_attr_config)
  Retr_Params <- proc.attr.hydfab::attr_cfig_parse(path_attr_config)
  datasets <- Retr_Params$datasets

  dir_dataset <- proc.attr.hydfab::std_dir_dataset(Retr_Params$paths$dir_std_base, datasets)

  # Retrieve the known valid gage_ids directly from rafts_prep standardized output!
  ls_rafts_std <- proc.attr.hydfab::proc_attr_read_gage_ids_fs(dir_dataset)

  featureSource <- ls_rafts_std$featureSource
  featureID <- ls_rafts_std$featureID
  rafts_path <- ls_rafts_std$path_dat_in


# Extract the valid gages from the standardized NetCDF dataset
  all_valid_gages <- ls_rafts_std$gage_ids

  # --- CRITICAL FIX FOR INTEGRATION TESTING ---
  # We must intersect the HydroATLAS COMIDs with our USGS Gage IDs.
  # To translate them, we use the mapping file generated by the training step!
  map_file <- base::file.path(Retr_Params$paths$dir_db_attrs, "meta_loc", "comid_featID_map.csv")

  if (base::file.exists(map_file)) {
    comid_map <- utils::read.csv(map_file, colClasses="character")

    # 1. Look up the path to the mock HydroATLAS data
    path_ha <- Retr_Params$paths$paths_ha[1]

    if (base::file.exists(path_ha)) {
      # 2. Open the mock dataset and get its column names
      ds_ha <- arrow::open_dataset(path_ha)
      ha_cols <- base::names(ds_ha)

      # 3. Dynamically detect the correct identifier column
      id_col <- "hf_id" # Default fallback
      for (c in c("hf_uid", "hf_id", "divide_id", "id")) {
        if (c %in% ha_cols) { id_col <- c; break }
      }

      # 4. Extract the raw COMIDs using the detected column
      ha_data <- ds_ha %>% dplyr::select(dplyr::all_of(id_col)) %>% dplyr::collect()
      ha_comids <- base::gsub("hf_id_", "", ha_data[[id_col]])
      ha_comids <- base::gsub("USGS-", "", ha_comids)

      # 5. Intersect the HydroATLAS COMIDs with our mapped COMIDs
      valid_comids <- base::intersect(comid_map$comid, ha_comids)

      # 6. Translate the safe COMIDs back to USGS gage_ids for sampling!
      safe_gages <- comid_map$gage_id[comid_map$comid %in% valid_comids]
    } else {
      safe_gages <- all_valid_gages
    }
  } else {
    safe_gages <- all_valid_gages
  }

  # Sample directly from the GUARANTEED safe dataset basins
  if(subsamp_n > 0){
    set.seed(subsamp_seed)
    actual_n <- base::min(subsamp_n, base::length(safe_gages))
    samp_locs <- base::sample(safe_gages, size=actual_n)
  } else {
    samp_locs <- safe_gages
  }
# # Extract the valid gages from the standardized NetCDF dataset
#   all_valid_gages <- ls_rafts_std$gage_ids

#   # --- CRITICAL FIX FOR INTEGRATION TESTING ---
#   # The mock testdata_20250901.zip only contains HydroATLAS attributes for 66 basins.
#   # We MUST ensure our random sample only selects basins that actually have data!

#   # 1. Look up the path to the mock HydroATLAS data
#   path_ha <- Retr_Params$paths$paths_ha
#   path_ha <- glue::glue(path_ha[1])

#   if (base::file.exists(path_ha)) {
#     # 2. Open the mock dataset and extract the raw IDs (which use the hf_id_ prefix)
#     ha_data <- arrow::open_dataset(path_ha) %>% dplyr::select(hf_id_divide_id) %>% dplyr::collect()

#     # 3. Clean the IDs to match our gage_ids format (strip the 'hf_id_' prefix)
#     ha_gages <- base::gsub("hf_id_", "", ha_data$hf_id_divide_id)

#     # 4. Intersect the two lists to find the guaranteed safe pool of basins
#     safe_gages <- base::intersect(all_valid_gages, ha_gages)
#   } else {
#     logr::log_print(glue::glue("WARNING: Mock HydroATLAS file not found at {path_ha}"), level="WARN")
#     safe_gages <- all_valid_gages
#   }

#   # Sample directly from the GUARANTEED safe dataset basins
#   if(subsamp_n > 0){
#     set.seed(subsamp_seed)
#     # Ensure we don't try to sample more basins than actually exist in the safe pool!
#     actual_n <- base::min(subsamp_n, base::length(safe_gages))
#     samp_locs <- base::sample(safe_gages, size=actual_n)
#   } else {
#     samp_locs <- safe_gages
#   }

  path_save_gpkg <- proc.attr.hydfab:::std_path_retr_gpkg(rafts_path)

  message(glue::glue("Processing {length(samp_locs)} valid locations..."))

  # Acquire the attributes for the sampled prediction locations
  dt_site_feat <- proc.attr.hydfab::proc_attr_gageids(gage_ids=samp_locs,
                                                      path_save_gpkg=path_save_gpkg,
                                                      featureSource=featureSource,
                                                      featureID=featureID,
                                                      Retr_Params=Retr_Params,
                                                      lyrs="network",
                                                      overwrite=FALSE)
  # We translate it dynamically using the original featureID format from rafts_prep
  #dt_site_feat$featureID <- base::as.character(glue::glue_data(dt_site_feat, featureID))
  dt_site_feat$featureSource <- featureSource

  # Extract the standardized directory base from the parsed attribute config
  dir_std_base <- Retr_Params$paths$dir_std_base
  ds_type <- base::unlist(cfig_pred)[['ds_type']]
  write_type <- 'parquet'

  dir_pred_meta <- glue::glue("{dir_std_base}/{datasets}")
  if(!dir.exists(dir_pred_meta)){
    dir.create(dir_pred_meta, recursive=TRUE)
  }

  for(ds in datasets){
    # Export the NLDI metadata file required by Python
    # glue::glue() will now successfully find 'dir_std_base' and 'ds' in the environment!
    path_nldi_out <- glue::glue(path_meta)
    proc.attr.hydfab::write_meta_nldi_feat(dt_site_feat=dt_site_feat,
                                           path_meta = path_nldi_out)
    print(glue::glue("Wrote NLDI metadata file to {path_nldi_out}"))
  }
}

main()
