# hfatl_rafts_config.yaml
# Configuration for formatting hfATLAS outputs into RaFTS-compatible inputs

file_io:
  dir_base: '~/noaa/regionalization/data/input'
  path_hfatlas_parquet: '{dir_base}/hfatlas/hf22_predictors_CONUS/final/hf22_predictors_CONUS_final.parquet'
  path_vpu_crosswalk: '' 
  dir_db_attrs: '{dir_base}/attributes_hfatl'
  
  # NEW: Path to save the placeholder metadata file
  path_meta_placeholder: '{dir_base}/user_data_std/{dataset_name}/nldi_feat_{dataset_name}_placeholder.parquet'

rafts_metadata:
  dataset_name: 'hfatlas' 
  featureSource: 'hf_id'
  data_source_flag: 'hfATLAS_v1'
