name: rafts_env
channels:
  - conda-forge

dependencies:
  - dask
  - duecredit
  - geopandas
  - joblib
  - mapie
  - matplotlib
  - multidict
  - netCDF4
  - numpy
  - pandas
<<<<<<< HEAD
  - pandera
=======
>>>>>>> cdab25e2 (cleaning up install guidance and related python install files)
  - pip
  - pyarrow
  - pydrive2
  - pynhd>=0.19.0
  - python=3.12
  - pyyaml
  - scikit-learn
  - seaborn
  - shapely
  - wheel
  - xarray
  - pip:
      - forestci==0.7
<<<<<<< HEAD
      - -e ../pkg/fs_prep
=======
      - -e ../pkg/fs_proc
>>>>>>> cdab25e2 (cleaning up install guidance and related python install files)
