# Prediction configuration file
# Note: This alternative configuration of the algo_config file was used in early August 2025 to perform process sensitivity analysis and assess uncertainty bounds.
name_attr_config: 'nex_test_attr_config.yaml'  # REQUIRED. Name of the corresponding dataset's attribute configuration file, which should be in the same directory as this. If not provided, assumes 'attr' may be substituted for this filename's 'algo'
name_algo_config: 'nex_test_algo_config_uncn.yaml' # REQUIRED. The name of the algorithm configuration file if in same directory as this config file. Otherwise the full path to the file.
name_tfrm_config: # 'xssaus_attrs_tform.yaml' # REQUIRED (if transforming predictor data). The name of transformation configuration file, stored in the same directory as the other config files.
ds_type: 'prediction' # Required string. Strongly recommended to select 'prediction' in the prediction config file. This string will be used in the filename of the output metadata describing each data point's identifer, COMID, lat/lon, reach name of the location. This string should differ from the string used in the attribute config yaml file. Filename: `"nldi_feat_{dataset}_{ds_type}.csv"` inside `dir_std_base / dataset /`.
write_type: 'parquet' # Required filetype for writing NLDI feature metadata. Default 'parquet'. May also select 'csv'
path_meta: "{dir_std_base}/../../raw/hfv4_vpu01_aug26_nexus/"  # Required. Prediction attribute metadata filepath formatted for R's glue() & py f-strings as generated using `proc.attr.hydfab::write_meta_nldi_feat()`. Fundamentally, this can be a path to any file containing the locations of interest. Strongly suggested default format when using proc.attr.hydfab:  "{dir_std_base}/{ds}/nldi_feat_{ds}_{ds_type}.{write_type}"
pred_file_comid_colname: 'nexus_id' # REQUIRED. The column name containing the location identifiers used for prediction in the prediction metadata file as defined above as path_meta.
path_gpkg_pred: "{home_dir}/noaa/hydrofabric/v4_aug26test/ngen_vpu01.gpkg" # Strongly recommended for custom prediction locations (e.g. aggregated locations). If not provided, the path_gpkg_fs_prep will be used, which may not have any required data points corresponding to prediction locations.
pred_gpkg_lyr: 'nexus' # The layer name to read from the prediction geopackage. Default None.
pred_gpkg_id_col: 'nexus_id' # The column name of the identifier inside path_gpkg_pred
path_crosswalk_ids: '{dir_std_base}/../../raw/crosswalks/hfv4_predictors_vpu01_nex_crosswalk.parquet' # '{dir_std_base}/{ds}/{ds}_crosswalk.parquet' # This gets generated by the build_nexus_crosswalk.py #'{dir_std_base}/../../raw/crosswalks/hf22_CONUS_huc12_crosswalk_24065c004f.parquet' # Optional. Path to the .parquet file used to crosswalk aggregated identifiers (e.g. huc12) to the standard identifier (e.g. divide_id). Used in fs_pair_donors.py
path_hf_finl_gpkg: '{home_dir}/noaa/hydrofabric/v4_aug26test/ngen_vpu01.gpkg' # Required when running fs_regn_params_gpkg.py The hydrofabric gpkg containing the divides specified in the path_crosswalk_ids. 
layr_hf_finl_gpkg: 'divides' # The layer to be read from the `path_hf_finl_gpkg`. Default 'divides'.
overwrite_sql: True # Recommended for fs_regn_params_gpkg.py. Should the sqlite tables for each parameter set be overwritten? Default False.
algo_response_vars: # List out the desired response variables (e.g. metrics, hydrologic signatures) for prediction. # TODO offer 'all'
  -  "spf_factor" 
  -  "frac_to_CR" 
  -  "a" 
  -  "b" 
  -  "smcmax_1" 
  -  "van_genuchten_alpha_1" 
  -  "hydraulic_conductivity_1" 
  -  "van_genuchten_n_1" 
  -  "field_capacity" 
  -  "van_genuchten_alpha_2" 
  -  "hydraulic_conductivity_2" 
  -  "van_genuchten_n_2" 
  -  "MFSNO" 
  -  "SCAMAX" 
  -  "RSURF_SNOW" 
  -  "CWP"
algo_type: # List out the algorithms desired for prediction (e.g. rf, mlp).  # TODO offer 'all'
  - 'rf'
algo_select: 'rf' # The specfic algorithm string to use for the final integration into the regionalization gpkg (ie a new layer added to the copy of path_hf_finl_gpkg). Used in fs_regn_params_gpkg.py.