# Config for grabbing catchment attributes corresponding to standard-named locations
# Two options exist for defining locations that need attributes. At least one must be used. Both may be used.
# Designed for the proc.attr.hydfab R package's script fs_attrs_grab.R to acquire attributes.
#  This config file is referenced in subsequent processing steps for consistency (e.g. file_io section)
# 1. Refer to a file/dataset {loc_id_filepath} with a column identifer {loc_id} representing a standardized location identifier.
# 2. Refer to a dataset processed by fs_prep python package and point to its location, {dir_std_base}/{datasets}, where {datasets} is a specific subdirectory name(s) or simply 'all'
# TODO is path_meta required for hfATLAS?
# TODO in the pred_config - can it use a directory for path_meta? What about two paths instead??

col_schema:   # required column mappings in the evaluation metrics dataset (if read in)
  - featureID: '{gage_id}' # python f-string / R glue() format; converting the 'gage_id' to the standardized featureID used by nhdplusTools/hydrofabric. Must use '{gage_id}' e.g. 'USGS-{gage_id}'
  - featureSource: 'hf_id' # The standardized nhdplusTools featureSource. Possible featureSources might be 'nwissite', 'comid', or 'hf_id'.
# loc_id_read: # This section only required for locations NOT to be read in under a standardized dataset location (dir_std_base). May be used for additional prediction locations. MUST leave each item name inside list with empty assignments if no datasets desired.
#   - gage_id: 'divide_id' # expects tabular dataset with this column name representing the location id.
#   - loc_id_filepath:  # Required. filepath. Allows reading of .csv or a dataset accessible using arrow::open_datast() in lieu of reading dataset generated by fs_prep.
#   - featureID_loc: '{gage_id}' # python f-string / R glue() format; converting the 'loc_id' to the standardized featureID used by nhdplusTools/hydrofabric. Must use '{loc_id}' e.g. 'USGS-{loc_id}'.
#   - featureSource_loc: 'hfuid' # The standardized nhdplusTools featureSource.
file_io: # May define {home_dir} for python's '{home_dir}/string_path'.format(home_dir =str(Path.home())) functionality # NOTE THAT ORDER MATTERS! If an f-string, or glue-formatted dir/path is defined, make sure references defined above it (unless it's {home_dir})
  - save_loc: 'local' #  #TODO implement once s3 becomes a capability. Use 'local' for saving to a local path via dir_save. Future work will create an approach for 'aws' or other cloud saving methods
  - home_dir: #OPTIONAL may optionally provide a home directory here, otherwise system default used.
  - dir_base: '{home_dir}/noaa/regionalization/data/' # Required. The save location of standardized output
  - dir_std_base: '{dir_base}/input/user_data_std' # Required. The location of standardized data generated by fs_prep python package
  - dir_db_attrs: '{dir_base}/input/attrs_hfatl/{ds}/' # Required. Should be a subdirectory of 'attributes' or 'attrs_hfatl/{ds}/'. The parent dir where each comid's attribute parquet file is stored in the subdirectory 'comid/', and each dataset's aggregated parquet attributes are stored in the subdirectory '/{dataset_name}
  - ds_type: 'training' # Required string. Recommended to select 'training' or 'prediction', but any string will work. This string will be used in the filename of the output metadata describing each data point's identifer, COMID, lat/lon, reach name of the location. This string should differ from the string used in the prediction config yaml file. Filename: `"nldi_feat_{dataset}_{ds_type}.csv"` inside `dir_std_base / dataset / `
  - write_type: 'parquet' # Required filetype for writing NLDI feature metadata. Default 'parquet'. May also select 'csv'
  - path_meta:  "{dir_std_base}/{ds}/nldi_feat_{ds}_{ds_type}.{write_type}"  #Required for legacy workflows, ignored when processing hfatlas data. Training attribute metadata filepath formatted for R's glue or py f-string, as generated using `proc.attr.hydfab::write_meta_nldi_feat()`. Strongly suggested default:  "{dir_std_base}/{ds}/nldi_feat_{ds}_{ds_type}.{write_type}"
  - name_tform_config: # 'xssa_attrs_tform.yaml' #Optional. The name of the transformation config file (if transformations desired). If specified, read the attribute requirements for transformation and ensure they are acquired as well.
  - name_prep_config: 'nex_test_agg_prep_config.yaml' # Required when running the hfatlas-based workflow
formulation_metadata:
  - datasets: # Required. Must match directory name inside dir_std_base. May be a list of items, or simply sublist 'all' to select everything inside dir_std_base for attribute grabbing.
    - 'nexus_test' # Required. In this example case, it's a sublist of just one thing.
  - formulation_base: 'casamnom' # Informational. Unique name of formulation. Optional.
attr_select: # Required. The names of variable sublistings are standardized with _vars, e.g. ha_vars, usgs_vars, sc_vars
  - hfatl_id_col: 'gageID_divide_id'
  - hfatl_id_format: 'USGS-{gage_id}_{divide_id}' #  The format used by the hfatl attribute data identifier column. This is only used in the fs_agg_nexus_hfatl.py workflow.
  - paths_hfatl: # Path to tabular HydrofabricATLAS parquet file of attributes extracted to hydrofabric divide
    - "{home_dir}/noaa/regionalization/data/raw/jul26cal_haftl_hfv4test/jul26_cal_hf4_predictors_300locations_final.parquet"
    - "{home_dir}/noaa/regionalization/data/raw/jul26cal_haftl_hfv4test/jul26_cal_hf4_parameters_300locations_final.parquet"
  - hfatl_vars:  # hydrofabricATLAS variables. Must specify paths_hfatl. Depends on fs_algo.utils.clean_hfatlas_columns
    - 'TOT_PPT9120_ANN_hfa' # PRISM precip 1990-2020
    - 'TOT_Wet_hfa' # Consecutive wet days (30 yr)
    - 'TOT_Dry_hfa'
    - 'TOT_AET_hfa' # Actual evapotranspiration
    - 'TOT_Intensity_hfa' # mm/day
    - 'TOT_RH_hfa' # relative humidity
    - 'TOT_BFI_hfa' # USGS modeled baseflow index
    - 'TOT_WB5100_yr_min_hfa' # Mean annual runoff 1951-2000
    - 'TOT_ELEV_MEAN_hfa'
    - 'TOT_RECHG_hfa'
    # - 'TOT_TWI_hfa' # TWI needs to be transformed into a mean value
    - 'TOT_TMIN7100_JAN_hfa'
    - 'TOT_PRSNOW_hfa'
    - 'TOT_IMPV01_hfa'
    - 'TOT_CLAYAVE_hfa' # 
    - 'TOT_SANDAVE_hfa'
    - 'TOT_AWCAVE_hfa'
    - 'glc_pc_c18_hfa' # percent cropland and shrubland/woodland (category 18)
    - 'TOT_EVI_JFM_2012_hfa' # Enhanced vegetation index winter 2012
    # Attributes from the nwmv4 static params parquet file:
    - 'ari_ix_stats' # aridity index
    - 'lka_stats' # Lake area percentage 
    - 'slp_dg_mean' # Mean slope, degrees
    - 'imperv_surf'
    - 'Forest_Cover_Extent_L07'
    - 'snw_pc_max'
    - 'area_sqkm'

