[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fs_algo"
dynamic = ["version"] 
description = "Formulation Selector Algorithm"
authors = [
    { name = "Guy Litt", email = "guy.litt@noaa.gov" }
]
license = { text = "MIT License" }
keywords = ["formulation", "algorithm", "evaluation"]
classifiers = [
    "Programming Language :: Python :: 3.12"
]
requires-python = "==3.12.11" 
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "xarray>=2025.7.1",
    "scikit-learn==1.5.2",
    "duecredit==0.10.2",
    "forestci==0.7",
    "mapie==0.9.2",
    "pyarrow>=17.0.0",
    "zarr>=2.18.3",
    "dask>=2024.10.0",
    "s3fs>=2024.10.0",
    "scipy>=1.14.1",
    "matplotlib==3.10.8",
    "pandera>=0.20.4",
    "pydantic>=2.9.2",
    "seaborn==0.13.2",
    "fs_prep" 
]

[project.urls]
Repository = "https://github.com/noaa-owp/formulation-selector"

# If fs_algo has any console scripts defined in its setup.py entry_points,
# you can define them here. If not, you can safely delete the [project.scripts] block.
[project.scripts]
fs_algo = "fs_algo.main:main" 

[tool.uv.sources]
fs_prep = { workspace = true }

# Translates find_packages(exclude=['tests*'])
[tool.hatch.build.targets.wheel]
packages = ["fs_algo"]
exclude = [
    "tests",
    "tests*",
]

[tool.hatch.version]
path = "fs_algo/__version__.py"

# Translates package_data={'fs_algo': ['data/*']}
#[tool.hatch.build.targets.wheel.force-include]
#"fs_algo/data" = "fs_algo/data"