"""fs_regn_params_gpkg.py

Unified script for extracting regionalized parameters and writing them as 
new attribute tables into a standalone SQLite database and a Master GeoPackage.

- Unsupervised (Clustering): Reads pre-compiled receiver_params generated by fs_pair_donors.py.
- Supervised (Regression): Horizontally merges individual parameter predictions 
  from fs_pred_algo.py and applies optional crosswalking.

The tables are written with 'divide_id' set as the formal index and include 
the algorithm string in the table name (e.g., formulation_algo). The script 
filters algorithms using wildcard matching from 'algo_select'.

Usage:
    >>> python fs_regn_params_gpkg.py "/path/to/pred_config.yaml"
"""

import argparse
import pandas as pd
from pathlib import Path
import logging
import sys
import shutil
import fnmatch

import fs_algo.utils as fsutil
import fs_prep.proc_eval_metrics as pem

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Write regionalized parameters to a standalone GeoPackage.')
    parser.add_argument('path_pred_config', type=str, help='Path to the prediction YAML config.')
    args = parser.parse_args()

    path_pred_config = Path(args.path_pred_config).expanduser()
    
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logging.info(f"Running fs_regn_params_gpkg.py using {path_pred_config.name}")

    # --- Parse Configurations ---
    pred_cfg = fsutil.PredConfigParser(path_pred_config)
    pred_cfg._read_pred_config()

    path_attr_config = fsutil.build_cfig_path(path_pred_config, pred_cfg.pred_cfg_dict.get('name_attr_config'))
    attr_cfig = fsutil.AttrConfigAndVars(path_attr_config)
    attr_cfig._read_attr_config()

    # Load Algo Config to determine if we are doing Supervised or Unsupervised writing
    path_algo_config = fsutil.build_cfig_path(path_pred_config, pred_cfg.pred_cfg_dict.get('name_algo_config'))
    algo_cfig = fsutil.AlgoConfigParser(path_algo_config)
    algo_cfig._read_algo_config()
    task_type = algo_cfig.algo_cfg_unc_dict["algo_cfg_dict"].get("task_type", "regression")
    
    dir_base = attr_cfig.attrs_cfg_dict.get('dir_base')
    dir_std_base = attr_cfig.attrs_cfg_dict.get('dir_std_base')
    dir_db_attrs = attr_cfig.attrs_cfg_dict.get('dir_db_attrs')
    datasets = attr_cfig.attrs_cfg_dict.get('datasets')
    home_dir = attr_cfig.attrs_cfg_dict.get('home_dir')
    
    context = {
        'dir_base': str(dir_base),
        'dir_std_base': str(dir_std_base),
        'dir_db_attrs': str(dir_db_attrs),
        'home_dir': str(home_dir),
    }

    # Fetch configuration variables
    overwrite_sql = pred_cfg.pred_cfg_dict.get('overwrite_sql', False)
    base_algos = pred_cfg.pred_cfg_dict.get('algo_type', [])
    resp_vars = pred_cfg.pred_cfg_dict.get('algo_response_vars', [])
    
    algo_select = pred_cfg.pred_cfg_dict.get('algo_select', [])
    if isinstance(algo_select, str):
        algo_select = [algo_select]

    # Locate the Prep Config to extract formulation ID
    try:
        name_prep_config = [x for x in attr_cfig.attr_config.get('file_io') if 'name_prep_config' in x][0]['name_prep_config']
        path_prep_config = fsutil.build_cfig_path(path_pred_config, name_prep_config)
        col_schema_df = pem.read_schm_ls_of_dict(path_prep_config)
        formulation_id = pem.std_form_id(col_schema_df)
        logging.info(f"Resolved base formulation name: {formulation_id}")
    except Exception as e:
        logging.error(f"Failed to resolve prep config or formulation ID: {e}")
        sys.exit(1)

    dirs_std_dict = fsutil.fs_save_algo_dir_struct(dir_base)
    dir_out = Path(dirs_std_dict.get('dir_out'))
    subdir = path_pred_config.parent.name
    dir_regionalization_sub = dir_out / "regionalization" / subdir
    dir_regionalization_sub.mkdir(parents=True, exist_ok=True)
    
    # Initialize Master GPKG Path
    path_hf_finl_gpkg_raw = pred_cfg.pred_cfg_dict.get('path_hf_finl_gpkg')
    if not path_hf_finl_gpkg_raw:
        logging.error("No 'path_hf_finl_gpkg' found in prediction config.")
        sys.exit(1)
        
    path_hf_finl_gpkg = Path(fsutil.resolve_fstrings(path_hf_finl_gpkg_raw, context))
    if not path_hf_finl_gpkg.exists():
        logging.error(f"Source Master GPKG does not exist: {path_hf_finl_gpkg}")
        sys.exit(1)

    # Ensure local Master GPKG copy exists
    dest_master_path = dir_regionalization_sub / path_hf_finl_gpkg.name.replace('.gpkg','_regn.gpkg')
    if not dest_master_path.exists(): 
        logging.info(f"Initializing local Master GPKG by copying {path_hf_finl_gpkg.name} to {dest_master_path.parent}")
        shutil.copy2(path_hf_finl_gpkg, dest_master_path)

    dir_regionalization_ds = dir_out / "regionalization"
    dir_out_alg_base = Path(dirs_std_dict.get('dir_out_alg_base'))

    # =========================================================================
    # Process Datasets and Write Tables
    # =========================================================================
    for ds in datasets:
        dir_ds_regn = dir_regionalization_ds / ds
        dir_out_alg_ds = dir_out_alg_base / ds
        
        logging.info(f"Processing {ds} dataset. Task Type: {task_type}")

        if task_type == 'clustering':
            # -----------------------------------------------------------------
            # UNSUPERVISED FLOW: Read pre-compiled donor-receiver tables
            # -----------------------------------------------------------------
            for resp_var in resp_vars:
                dynamic_algos = fsutil.discover_dynamic_algos(
                    search_dir=dir_out_alg_ds,
                    base_algos=base_algos,
                    metric=resp_var,
                    dataset_id=ds,
                    file_prefix="algo_",
                    file_extension=".joblib"
                )

                for algo in dynamic_algos:
                    # --- APPLY ALGO_SELECT FILTER ---
                    if algo_select:
                        matched = any(fnmatch.fnmatch(algo, pattern) for pattern in algo_select)
                        if not matched:
                            logging.info(f"Algorithm '{algo}' skipped (does not match 'algo_select' patterns).")
                            continue

                    param_file_mapped = dir_ds_regn / f"receiver_params_mapped_{algo}_{resp_var}__{ds}.parquet"
                    param_file_std = dir_ds_regn / f"receiver_params_{algo}_{resp_var}__{ds}.csv"

                    if param_file_mapped.exists():
                        param_file = param_file_mapped
                    elif param_file_std.exists():
                        param_file = param_file_std
                    else:
                        logging.error(f"No parameter files found for {algo} and {resp_var} in {dir_ds_regn}")
                        continue
                        
                    logging.info(f"Loading regionalized parameters from {param_file.name}")
                    if param_file.suffix == '.parquet':
                        df_params = pd.read_parquet(param_file)
                    else:
                        df_params = pd.read_csv(param_file)

                    id_col = pred_gpkg_id_col if pred_gpkg_id_col in df_params.columns else 'featureID'
                    if id_col not in df_params.columns:
                        id_col = df_params.columns[0]
                        logging.warning(f"Expected identifier column not found. Defaulting to first column: '{id_col}'.")
                        
                    # Dynamically generate table and file names
                    table_name = f"{formulation_id}_{algo}"
                    path_output_sql = dir_regionalization_sub / f"compiled_regionalized_params_{algo}.sqlite"
                    
                    # Write/Append to Local SQLite DB & Master GPKG
                    fsutil.update_database(path_output_sql, df_params, table_name, id_col, overwrite_sql)
                    fsutil.update_database(dest_master_path, df_params, table_name, id_col, overwrite_sql)
                    logging.info(f"Updated hydrofabric geopackage at {dest_master_path} with table '{table_name}'")
                    
        else:
            # -----------------------------------------------------------------
            # SUPERVISED FLOW: Horizontally merge individual parameter predictions
            # -----------------------------------------------------------------
            if not resp_vars:
                logging.error("No response variables defined in config to compile.")
                continue

            for algo in base_algos:
                # --- APPLY ALGO_SELECT FILTER ---
                if algo_select:
                    matched = any(fnmatch.fnmatch(algo, pattern) for pattern in algo_select)
                    if not matched:
                        logging.info(f"Algorithm '{algo}' skipped (does not match 'algo_select' patterns).")
                        continue

                logging.info(f"Compiling supervised predictions for algorithm: {algo}")
                df_compiled_params = pd.DataFrame()
                id_col_pred = pred_cfg.pred_cfg_dict.get('pred_file_comid_colname', 'featureID')
                
                # Compile all parameter predictions into a single wide DataFrame
                for resp_var in resp_vars:
                    pred_path = fsutil.std_pred_path(dir_out=dir_out, algo=algo, metric=resp_var, dataset_id=ds)
                    
                    if not pred_path.exists():
                        logging.error(f"Prediction file missing for parameter '{resp_var}': {pred_path}")
                        continue
                        
                    df_pred = pd.read_parquet(pred_path)
                    
                    if 'prediction' not in df_pred.columns:
                        logging.warning(f"No 'prediction' column found in {pred_path.name}. Skipping.")
                        continue
                    
                    current_id_col = 'featureID' if 'featureID' in df_pred.columns else id_col_pred
                    df_sub = df_pred[[current_id_col, 'prediction']].rename(columns={'prediction': resp_var})
                    
                    if df_compiled_params.empty:
                        df_compiled_params = df_sub
                    else:
                        df_compiled_params = df_compiled_params.merge(df_sub, on=current_id_col, how='outer')
                
                if df_compiled_params.empty:
                    logging.warning(f"Failed to compile any parameters for algorithm {algo}. Skipping database update.")
                    continue
                    
                # OPTIONAL CROSSWALK MAPPING
                path_crosswalk_ids_raw = pred_cfg.pred_cfg_dict.get('path_crosswalk_ids')
                pred_gpkg_id_col = pred_cfg.pred_cfg_dict.get('pred_gpkg_id_col')
                
                if path_crosswalk_ids_raw:
                    path_crosswalk_ids = Path(fsutil.resolve_fstrings(path_crosswalk_ids_raw, context))
                    if path_crosswalk_ids.exists():
                        logging.info(f"Applying crosswalk mapping from {path_crosswalk_ids}")
                        
                        df_crosswalk = pd.read_parquet(path_crosswalk_ids).astype(str) if str(path_crosswalk_ids).endswith('.parquet') else pd.read_csv(path_crosswalk_ids, dtype=str)
                        
                        crosswalk_cols = list(df_crosswalk.columns)
                        if pred_gpkg_id_col in crosswalk_cols:
                            crosswalk_cols.remove(pred_gpkg_id_col)
                            desired_id_col = crosswalk_cols[0] 
                            
                            df_compiled_params[current_id_col] = df_compiled_params[current_id_col].astype(str)
                            
                            df_compiled_params = df_compiled_params.merge(
                                df_crosswalk, left_on=current_id_col, right_on=pred_gpkg_id_col, how='inner'
                            )
                            
                            cols_to_drop = [current_id_col]
                            if pred_gpkg_id_col in df_compiled_params.columns and pred_gpkg_id_col != desired_id_col:
                                cols_to_drop.append(pred_gpkg_id_col)
                                
                            df_compiled_params = df_compiled_params.drop(columns=cols_to_drop, errors='ignore')
                            new_col_order = [desired_id_col] + [c for c in df_compiled_params.columns if c != desired_id_col]
                            df_compiled_params = df_compiled_params[new_col_order]
                            
                            current_id_col = desired_id_col
                        else:
                            logging.error(f"Crosswalk file missing the specified pred_gpkg_id_col: {pred_gpkg_id_col}")
                    else:
                        logging.error(f"Crosswalk file path was provided but does not exist: {path_crosswalk_ids}")

                id_col = pred_gpkg_id_col if pred_gpkg_id_col in df_compiled_params.columns else current_id_col
                table_name = f"{formulation_id}_{algo}"
                path_output_sql = dir_regionalization_sub / f"compiled_supervised_params_{algo}.sqlite"
                
                # Write/Append to Local SQLite DB & Master GPKG
                fsutil.update_database(path_output_sql, df_compiled_params, table_name, id_col, overwrite_sql)
                fsutil.update_database(dest_master_path, df_compiled_params, table_name, id_col, overwrite_sql)
                logging.info(f"Updated hydrofabric geopackage at {dest_master_path} with table '{table_name}'")

    logging.info("FINISHED writing and transferring parameters to GeoPackages.")