[project]
name = "formulation-selector"
version = "0.1.0"
requires-python = "==3.12.11" 
dependencies = [
    "fs_algo",
    "fs_prep",
    "xgboost>=3.4.0",
]

[tool.uv.workspace]
members = [
    "fs_algo",
    "fs_prep"
]

# Tell the root project to look in the local workspace for these packages
[tool.uv.sources]
fs_algo = { workspace = true }
fs_prep = { workspace = true }

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]
spyder = [
  "spyder-kernels; platform_system == 'Windows'"
]
